/*
 * This file is generated by jOOQ.
*/
package moccasin.moccasin.model.jooq.icd;


import javax.annotation.Generated;

import moccasin.moccasin.model.jooq.icd.tables.Chapters;
import moccasin.moccasin.model.jooq.icd.tables.Groups;
import moccasin.moccasin.model.jooq.icd.tables.IcdCodes;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling indexes of tables of the <code>icd</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index KAPX = Indexes0.KAPX;
    public static final Index GRX = Indexes0.GRX;
    public static final Index CODEOHNEPUNKTX = Indexes0.CODEOHNEPUNKTX;
    public static final Index CODEX = Indexes0.CODEX;
    public static final Index EBENEX = Indexes0.EBENEX;
    public static final Index NORMCODEX = Indexes0.NORMCODEX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index KAPX = createIndex("kapx", Chapters.CHAPTERS, new OrderField[] { Chapters.CHAPTERS.KAPNR }, true);
        public static Index GRX = createIndex("grx", Groups.GROUPS, new OrderField[] { Groups.GROUPS.GRVON }, true);
        public static Index CODEOHNEPUNKTX = createIndex("codeohnepunktx", IcdCodes.ICD_CODES, new OrderField[] { IcdCodes.ICD_CODES.CODEOHNEPUNKT }, true);
        public static Index CODEX = createIndex("codex", IcdCodes.ICD_CODES, new OrderField[] { IcdCodes.ICD_CODES.CODE }, true);
        public static Index EBENEX = createIndex("ebenex", IcdCodes.ICD_CODES, new OrderField[] { IcdCodes.ICD_CODES.EBENE }, false);
        public static Index NORMCODEX = createIndex("normcodex", IcdCodes.ICD_CODES, new OrderField[] { IcdCodes.ICD_CODES.NORMCODE }, true);
    }
}
