/*
 * This file is generated by jOOQ.
*/
package moccasin.moccasin.model.jooq.icd;


import javax.annotation.Generated;

import moccasin.moccasin.model.jooq.icd.tables.Chapters;
import moccasin.moccasin.model.jooq.icd.tables.Groups;
import moccasin.moccasin.model.jooq.icd.tables.IcdCodes;
import moccasin.moccasin.model.jooq.icd.tables.records.ChaptersRecord;
import moccasin.moccasin.model.jooq.icd.tables.records.GroupsRecord;
import moccasin.moccasin.model.jooq.icd.tables.records.IcdCodesRecord;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>icd</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChaptersRecord> KAPX = UniqueKeys0.KAPX;
    public static final UniqueKey<GroupsRecord> GRX = UniqueKeys0.GRX;
    public static final UniqueKey<IcdCodesRecord> CODEX = UniqueKeys0.CODEX;
    public static final UniqueKey<IcdCodesRecord> NORMCODEX = UniqueKeys0.NORMCODEX;
    public static final UniqueKey<IcdCodesRecord> CODEOHNEPUNKTX = UniqueKeys0.CODEOHNEPUNKTX;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<GroupsRecord, ChaptersRecord> GROUPS__KGRX = ForeignKeys0.GROUPS__KGRX;
    public static final ForeignKey<IcdCodesRecord, ChaptersRecord> ICD_CODES__CODESKAPITEL = ForeignKeys0.ICD_CODES__CODESKAPITEL;
    public static final ForeignKey<IcdCodesRecord, GroupsRecord> ICD_CODES__CODESGRUPPEN = ForeignKeys0.ICD_CODES__CODESGRUPPEN;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<ChaptersRecord> KAPX = createUniqueKey(Chapters.CHAPTERS, "kapx", Chapters.CHAPTERS.KAPNR);
        public static final UniqueKey<GroupsRecord> GRX = createUniqueKey(Groups.GROUPS, "grx", Groups.GROUPS.GRVON);
        public static final UniqueKey<IcdCodesRecord> CODEX = createUniqueKey(IcdCodes.ICD_CODES, "codex", IcdCodes.ICD_CODES.CODE);
        public static final UniqueKey<IcdCodesRecord> NORMCODEX = createUniqueKey(IcdCodes.ICD_CODES, "normcodex", IcdCodes.ICD_CODES.NORMCODE);
        public static final UniqueKey<IcdCodesRecord> CODEOHNEPUNKTX = createUniqueKey(IcdCodes.ICD_CODES, "codeohnepunktx", IcdCodes.ICD_CODES.CODEOHNEPUNKT);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<GroupsRecord, ChaptersRecord> GROUPS__KGRX = createForeignKey(moccasin.moccasin.model.jooq.icd.Keys.KAPX, Groups.GROUPS, "groups__kgrx", Groups.GROUPS.KAPNR);
        public static final ForeignKey<IcdCodesRecord, ChaptersRecord> ICD_CODES__CODESKAPITEL = createForeignKey(moccasin.moccasin.model.jooq.icd.Keys.KAPX, IcdCodes.ICD_CODES, "icd_codes__codeskapitel", IcdCodes.ICD_CODES.KAPNR);
        public static final ForeignKey<IcdCodesRecord, GroupsRecord> ICD_CODES__CODESGRUPPEN = createForeignKey(moccasin.moccasin.model.jooq.icd.Keys.GRX, IcdCodes.ICD_CODES, "icd_codes__codesgruppen", IcdCodes.ICD_CODES.GRVON);
    }
}
