/*
 * This file is generated by jOOQ.
*/
package moccasin.moccasin.model.jooq.icd;


import javax.annotation.Generated;

import moccasin.moccasin.model.jooq.icd.tables.Chapters;
import moccasin.moccasin.model.jooq.icd.tables.Groups;
import moccasin.moccasin.model.jooq.icd.tables.IcdCodes;


/**
 * Convenience access to all tables in icd
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>icd.chapters</code>.
     */
    public static final Chapters CHAPTERS = moccasin.moccasin.model.jooq.icd.tables.Chapters.CHAPTERS;

    /**
     * The table <code>icd.groups</code>.
     */
    public static final Groups GROUPS = moccasin.moccasin.model.jooq.icd.tables.Groups.GROUPS;

    /**
     * The table <code>icd.icd_codes</code>.
     */
    public static final IcdCodes ICD_CODES = moccasin.moccasin.model.jooq.icd.tables.IcdCodes.ICD_CODES;
}
