/*
 * This file is generated by jOOQ.
*/
package moccasin.moccasin.model.jooq.icd.tables.records;


import javax.annotation.Generated;

import moccasin.moccasin.model.jooq.icd.tables.IcdCodes;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IcdCodesRecord extends UpdatableRecordImpl<IcdCodesRecord> {

    private static final long serialVersionUID = 361291291;

    /**
     * Setter for <code>icd.icd_codes.ebene</code>.
     */
    public void setEbene(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>icd.icd_codes.ebene</code>.
     */
    public String getEbene() {
        return (String) get(0);
    }

    /**
     * Setter for <code>icd.icd_codes.ort</code>.
     */
    public void setOrt(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>icd.icd_codes.ort</code>.
     */
    public String getOrt() {
        return (String) get(1);
    }

    /**
     * Setter for <code>icd.icd_codes.art</code>.
     */
    public void setArt(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>icd.icd_codes.art</code>.
     */
    public String getArt() {
        return (String) get(2);
    }

    /**
     * Setter for <code>icd.icd_codes.kapnr</code>.
     */
    public void setKapnr(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>icd.icd_codes.kapnr</code>.
     */
    public String getKapnr() {
        return (String) get(3);
    }

    /**
     * Setter for <code>icd.icd_codes.grvon</code>.
     */
    public void setGrvon(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>icd.icd_codes.grvon</code>.
     */
    public String getGrvon() {
        return (String) get(4);
    }

    /**
     * Setter for <code>icd.icd_codes.code</code>.
     */
    public void setCode(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>icd.icd_codes.code</code>.
     */
    public String getCode() {
        return (String) get(5);
    }

    /**
     * Setter for <code>icd.icd_codes.normcode</code>.
     */
    public void setNormcode(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>icd.icd_codes.normcode</code>.
     */
    public String getNormcode() {
        return (String) get(6);
    }

    /**
     * Setter for <code>icd.icd_codes.codeohnepunkt</code>.
     */
    public void setCodeohnepunkt(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>icd.icd_codes.codeohnepunkt</code>.
     */
    public String getCodeohnepunkt() {
        return (String) get(7);
    }

    /**
     * Setter for <code>icd.icd_codes.titel</code>.
     */
    public void setTitel(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>icd.icd_codes.titel</code>.
     */
    public String getTitel() {
        return (String) get(8);
    }

    /**
     * Setter for <code>icd.icd_codes.dreisteller</code>.
     */
    public void setDreisteller(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>icd.icd_codes.dreisteller</code>.
     */
    public String getDreisteller() {
        return (String) get(9);
    }

    /**
     * Setter for <code>icd.icd_codes.viersteller</code>.
     */
    public void setViersteller(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>icd.icd_codes.viersteller</code>.
     */
    public String getViersteller() {
        return (String) get(10);
    }

    /**
     * Setter for <code>icd.icd_codes.fünfsteller</code>.
     */
    public void setFünfsteller(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>icd.icd_codes.fünfsteller</code>.
     */
    public String getFünfsteller() {
        return (String) get(11);
    }

    /**
     * Setter for <code>icd.icd_codes.p295</code>.
     */
    public void setP295(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>icd.icd_codes.p295</code>.
     */
    public String getP295() {
        return (String) get(12);
    }

    /**
     * Setter for <code>icd.icd_codes.p301</code>.
     */
    public void setP301(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>icd.icd_codes.p301</code>.
     */
    public String getP301() {
        return (String) get(13);
    }

    /**
     * Setter for <code>icd.icd_codes.mortl1code</code>.
     */
    public void setMortl1code(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>icd.icd_codes.mortl1code</code>.
     */
    public String getMortl1code() {
        return (String) get(14);
    }

    /**
     * Setter for <code>icd.icd_codes.mortl2code</code>.
     */
    public void setMortl2code(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>icd.icd_codes.mortl2code</code>.
     */
    public String getMortl2code() {
        return (String) get(15);
    }

    /**
     * Setter for <code>icd.icd_codes.mortl3code</code>.
     */
    public void setMortl3code(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>icd.icd_codes.mortl3code</code>.
     */
    public String getMortl3code() {
        return (String) get(16);
    }

    /**
     * Setter for <code>icd.icd_codes.mortl4code</code>.
     */
    public void setMortl4code(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>icd.icd_codes.mortl4code</code>.
     */
    public String getMortl4code() {
        return (String) get(17);
    }

    /**
     * Setter for <code>icd.icd_codes.morblcode</code>.
     */
    public void setMorblcode(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>icd.icd_codes.morblcode</code>.
     */
    public String getMorblcode() {
        return (String) get(18);
    }

    /**
     * Setter for <code>icd.icd_codes.sexcode</code>.
     */
    public void setSexcode(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>icd.icd_codes.sexcode</code>.
     */
    public String getSexcode() {
        return (String) get(19);
    }

    /**
     * Setter for <code>icd.icd_codes.sexfehlertyp</code>.
     */
    public void setSexfehlertyp(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>icd.icd_codes.sexfehlertyp</code>.
     */
    public String getSexfehlertyp() {
        return (String) get(20);
    }

    /**
     * Setter for <code>icd.icd_codes.altuntneu</code>.
     */
    public void setAltuntneu(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>icd.icd_codes.altuntneu</code>.
     */
    public String getAltuntneu() {
        return (String) get(21);
    }

    /**
     * Setter for <code>icd.icd_codes.altobneu</code>.
     */
    public void setAltobneu(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>icd.icd_codes.altobneu</code>.
     */
    public String getAltobneu() {
        return (String) get(22);
    }

    /**
     * Setter for <code>icd.icd_codes.altfehlertyp</code>.
     */
    public void setAltfehlertyp(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>icd.icd_codes.altfehlertyp</code>.
     */
    public String getAltfehlertyp() {
        return (String) get(23);
    }

    /**
     * Setter for <code>icd.icd_codes.exot</code>.
     */
    public void setExot(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>icd.icd_codes.exot</code>.
     */
    public String getExot() {
        return (String) get(24);
    }

    /**
     * Setter for <code>icd.icd_codes.belegt</code>.
     */
    public void setBelegt(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>icd.icd_codes.belegt</code>.
     */
    public String getBelegt() {
        return (String) get(25);
    }

    /**
     * Setter for <code>icd.icd_codes.ifsgmeldung</code>.
     */
    public void setIfsgmeldung(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>icd.icd_codes.ifsgmeldung</code>.
     */
    public String getIfsgmeldung() {
        return (String) get(26);
    }

    /**
     * Setter for <code>icd.icd_codes.ifsglabor</code>.
     */
    public void setIfsglabor(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>icd.icd_codes.ifsglabor</code>.
     */
    public String getIfsglabor() {
        return (String) get(27);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IcdCodesRecord
     */
    public IcdCodesRecord() {
        super(IcdCodes.ICD_CODES);
    }

    /**
     * Create a detached, initialised IcdCodesRecord
     */
    public IcdCodesRecord(String ebene, String ort, String art, String kapnr, String grvon, String code, String normcode, String codeohnepunkt, String titel, String dreisteller, String viersteller, String fünfsteller, String p295, String p301, String mortl1code, String mortl2code, String mortl3code, String mortl4code, String morblcode, String sexcode, String sexfehlertyp, String altuntneu, String altobneu, String altfehlertyp, String exot, String belegt, String ifsgmeldung, String ifsglabor) {
        super(IcdCodes.ICD_CODES);

        set(0, ebene);
        set(1, ort);
        set(2, art);
        set(3, kapnr);
        set(4, grvon);
        set(5, code);
        set(6, normcode);
        set(7, codeohnepunkt);
        set(8, titel);
        set(9, dreisteller);
        set(10, viersteller);
        set(11, fünfsteller);
        set(12, p295);
        set(13, p301);
        set(14, mortl1code);
        set(15, mortl2code);
        set(16, mortl3code);
        set(17, mortl4code);
        set(18, morblcode);
        set(19, sexcode);
        set(20, sexfehlertyp);
        set(21, altuntneu);
        set(22, altobneu);
        set(23, altfehlertyp);
        set(24, exot);
        set(25, belegt);
        set(26, ifsgmeldung);
        set(27, ifsglabor);
    }
}
