/*
 * This file is generated by jOOQ.
*/
package moccasin.moccasin.model.jooq.atc;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import moccasin.moccasin.model.jooq.DefaultCatalog;
import moccasin.moccasin.model.jooq.atc.tables.AtcCodes;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Atc extends SchemaImpl {

    private static final long serialVersionUID = 927186166;

    /**
     * The reference instance of <code>atc</code>
     */
    public static final Atc ATC = new Atc();

    /**
     * The table <code>atc.atc_codes</code>.
     */
    public final AtcCodes ATC_CODES = moccasin.moccasin.model.jooq.atc.tables.AtcCodes.ATC_CODES;

    /**
     * No further instances allowed
     */
    private Atc() {
        super("atc", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            AtcCodes.ATC_CODES);
    }
}
