/*
 * This file is generated by jOOQ.
*/
package moccasin.moccasin.model.jooq.atc;


import javax.annotation.Generated;

import moccasin.moccasin.model.jooq.atc.tables.AtcCodes;
import moccasin.moccasin.model.jooq.atc.tables.records.AtcCodesRecord;

import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>atc</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AtcCodesRecord> ATC_CODES_ATC_CODE_PK = UniqueKeys0.ATC_CODES_ATC_CODE_PK;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<AtcCodesRecord> ATC_CODES_ATC_CODE_PK = createUniqueKey(AtcCodes.ATC_CODES, "atc_codes_ATC-Code_pk", AtcCodes.ATC_CODES.ATC_CODE);
    }
}
