/*
 * This file is generated by jOOQ.
*/
package moccasin.moccasin.model.jooq.atc;


import javax.annotation.Generated;

import moccasin.moccasin.model.jooq.atc.tables.AtcCodes;


/**
 * Convenience access to all tables in atc
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>atc.atc_codes</code>.
     */
    public static final AtcCodes ATC_CODES = moccasin.moccasin.model.jooq.atc.tables.AtcCodes.ATC_CODES;
}
