/*
 * This file is generated by jOOQ.
*/
package moccasin.moccasin.model.jooq.atc.tables.records;


import javax.annotation.Generated;

import moccasin.moccasin.model.jooq.atc.tables.AtcCodes;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AtcCodesRecord extends UpdatableRecordImpl<AtcCodesRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = 751844138;

    /**
     * Setter for <code>atc.atc_codes.ATC-Code</code>.
     */
    public void setAtcCode(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>atc.atc_codes.ATC-Code</code>.
     */
    public String getAtcCode() {
        return (String) get(0);
    }

    /**
     * Setter for <code>atc.atc_codes.bedeutung</code>.
     */
    public void setBedeutung(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>atc.atc_codes.bedeutung</code>.
     */
    public String getBedeutung() {
        return (String) get(1);
    }

    /**
     * Setter for <code>atc.atc_codes.DDD-Info</code>.
     */
    public void setDddInfo(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>atc.atc_codes.DDD-Info</code>.
     */
    public String getDddInfo() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return AtcCodes.ATC_CODES.ATC_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return AtcCodes.ATC_CODES.BEDEUTUNG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return AtcCodes.ATC_CODES.DDD_INFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getAtcCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getBedeutung();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDddInfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getAtcCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getBedeutung();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDddInfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AtcCodesRecord value1(String value) {
        setAtcCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AtcCodesRecord value2(String value) {
        setBedeutung(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AtcCodesRecord value3(String value) {
        setDddInfo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AtcCodesRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AtcCodesRecord
     */
    public AtcCodesRecord() {
        super(AtcCodes.ATC_CODES);
    }

    /**
     * Create a detached, initialised AtcCodesRecord
     */
    public AtcCodesRecord(String atcCode, String bedeutung, String dddInfo) {
        super(AtcCodes.ATC_CODES);

        set(0, atcCode);
        set(1, bedeutung);
        set(2, dddInfo);
    }
}
